apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      components: frontend
  template:
    metadata:
      labels:
        components: frontend
    spec:
      containers:
        - name: short-cat
          image: antonlarichev/short-app:v1.0
          #imagePullPolicy: Always #постоянно выкатывать обновление имеджа применяется обычно с  image-latest
          ports: 
            - containerPort: 80
          resources:
            limits:
              memory: "400Mi"
              cpu: "500m"