apiVersion: v1
kind: Pod
metadata:
  name: short-cat
  labels:
    components: frontend
spec:
  containers:
    - name: short-cat
      image: antonlarichev/short-app
      ports: 
        - containerPort: 80
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"