apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: apishort
  template:
    metadata:
      labels:
        components: apishort
    spec:
      containers:
        - name: api-short-cat
          image: antonlarichev/short-api:v1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "400Mi"
              cpu: 300m
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-for-api
                  key: DATABASE_URL
          volumeMounts:
            - name: testvolume
              mountPath: /etc/test
              readOnly: true
          livenessProbe:
            # httpGet:
            exec:
              command:
                - curl 
                - --fail
                - http://localhost:3000/api
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          redinessProbe:
            exec:
              command:
                - curl 
                - --fail
                - http://localhost:3000/api
            periodSeconds: 5
            failureThreshold: 5
      volumes:
        - name: testvolume
          configMap:
            name: test-config-map     
# DATABASE url
# postgres://user:passord@url:5432/db